export const list = [
  { name: 'anhui', label: '安徽' },
  { name: 'beijing', label: '北京' },
  { name: 'fujian', label: '福建' },
  { name: 'gansu', label: '甘肃' },
  { name: 'guangdong', label: '广东' },
  { name: 'guangxi', label: '广西' },
  { name: 'guizhou', label: '贵州' },
  { name: 'hainan', label: '海南' },
  { name: 'hebei', label: '河北' },
  { name: 'henan', label: '河南' },
  { name: 'heilongjiang', label: '黑龙江' },
  { name: 'hubei', label: '湖北' },
  { name: 'hunan', label: '湖南' },
  { name: 'jilin', label: '吉林' },
  { name: 'jiangsu', label: '江苏' },
  { name: 'jiangxi', label: '江西' },
  { name: 'liaoning', label: '辽宁' },
  { name: 'inner Mongolia', label: '内蒙古' },
  { name: 'ningxia', label: '宁夏' },
  { name: 'qinghai', label: '青海' },
  { name: 'shandong', label: '山东' },
  { name: 'shanxi', label: '山西' },
  { name: 'shaanxi', label: '陕西' },
  { name: 'shanghai', label: '上海' },
  { name: 'sichuan', label: '四川' },
  { name: 'tianjin', label: '天津' },
  { name: 'tibet', label: '西藏' },
  { name: 'xinjiang', label: '新疆' },
  { name: 'yunnan', label: '云南' },
  { name: 'zhejiang', label: '浙江' },
  { name: 'chongqing', label: '重庆' },
  { name: 'hongkong', label: '香港' },
  { name: 'macao', label: '澳门' },
  { name: 'taiwan', label: '台湾' },
  { name: 'shenzhen', label: '深圳' },
];
